
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url:  jdbc:mysql://localhost:3306/beauty?serviceTimezone=UTC
      username: root
      password: wu@xiaoting0308@
  main:
    allow-circular-references: true




#spring:
#  profiles:
#    active: dev
#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#server:
#  port: 80
#
#---
#spring:
#  config:
#    activate:
#      on-profile: pro
#server:
server:
  port: 82
mybatis:
  mapper-locations: classpath:com/itheima/springboot_01_ssm_startquick/mapper/**/*.xml
#  port: 82